"""Port of the core `@cordisjs/plugin-hmr` behavior — module change reloads,
covering both the event-driven (watchdog) and polling watcher paths."""

import asyncio
import os

import plugkit.cordis.hmr as hmr_module

from plugkit.cordis import Context
from plugkit.cordis.hmr import Hmr
from plugkit.cordis.timer import TimerService, set_clock

from .conftest import Mock, sleep
from .fake_clock import FakeClock
from .loader_utils import install

FIXTURES = os.path.join(os.path.dirname(os.path.abspath(__file__)), "fixtures")
HMR_PLUGIN = os.path.join(FIXTURES, "hmr_plugin.py")


def write_hmr_plugin(value):
    import sys

    # drop the module so each test imports the fresh file contents
    sys.modules.pop("plugkit.tests.fixtures.hmr_plugin", None)
    with open(HMR_PLUGIN, "w", encoding="utf-8") as file:
        file.write(f'''"""HMR test fixture — regenerated by the test suite."""

name = "hmr-test"

value = {value!r}


def apply(ctx, config):
    ctx.on("hmr/get-value", lambda: value)
''')


def touch_hmr_plugin(value):
    write_hmr_plugin(value)
    # bump mtime deterministically
    stat = os.stat(HMR_PLUGIN)
    os.utime(HMR_PLUGIN, (stat.st_atime + 2, stat.st_mtime + 2))


def write_raw(content):
    with open(HMR_PLUGIN, "w", encoding="utf-8") as file:
        file.write(content)
    # bump mtime deterministically
    stat = os.stat(HMR_PLUGIN)
    os.utime(HMR_PLUGIN, (stat.st_atime + 2, stat.st_mtime + 2))


async def test_hmr_reloads_changed_plugin(monkeypatch):
    monkeypatch.setattr(hmr_module, "WATCHDOG_AVAILABLE", False)
    write_hmr_plugin("first")
    try:
        clock = FakeClock()
        set_clock(clock)
        ctx = Context()
        loader = await install(ctx)
        loader.modules["__cordis_timer__"] = TimerService
        loader.modules["hmr"] = Hmr
        await loader.create({"name": "__cordis_timer__"})
        await loader.create({"name": "hmr", "config": {"debounce": 10}})
        await loader.create({"name": "plugkit.tests.fixtures.hmr_plugin"})
        for _ in range(50):
            await sleep()
        # let the poll register file snapshots before the change
        for _ in range(3):
            await clock.advance(20)
        assert ctx.bail("hmr/get-value") == "first"

        touch_hmr_plugin("second")
        for _ in range(50):
            await clock.advance(20)
        assert ctx.bail("hmr/get-value") == "second"
    finally:
        set_clock(None)
        os.path.exists(HMR_PLUGIN) and os.remove(HMR_PLUGIN)


async def test_hmr_emits_change_event(monkeypatch):
    monkeypatch.setattr(hmr_module, "WATCHDOG_AVAILABLE", False)
    write_hmr_plugin("first")
    try:
        clock = FakeClock()
        set_clock(clock)
        ctx = Context()
        loader = await install(ctx)
        loader.modules["__cordis_timer__"] = TimerService
        loader.modules["hmr"] = Hmr
        changes = []
        ctx.on("hmr/change", lambda names: changes.append(names))
        await loader.create({"name": "__cordis_timer__"})
        await loader.create({"name": "hmr", "config": {"debounce": 10}})
        await loader.create({"name": "plugkit.tests.fixtures.hmr_plugin"})
        for _ in range(50):
            await sleep()
        # let the poll register file snapshots before the change
        for _ in range(3):
            await clock.advance(20)

        touch_hmr_plugin("second")
        for _ in range(50):
            await clock.advance(20)
        assert any("plugkit.tests.fixtures.hmr_plugin" in names for names in changes)
    finally:
        set_clock(None)
        os.path.exists(HMR_PLUGIN) and os.remove(HMR_PLUGIN)


async def test_hmr_watchdog_events():
    write_hmr_plugin("first")
    try:
        ctx = Context()
        loader = await install(ctx)
        loader.modules["__cordis_timer__"] = TimerService
        loader.modules["hmr"] = Hmr
        await loader.create({"name": "__cordis_timer__"})
        await loader.create({"name": "hmr", "config": {"debounce": 10, "root": ["."]}})
        await loader.create({"name": "plugkit.tests.fixtures.hmr_plugin"})
        for _ in range(50):
            await sleep()
        assert ctx.bail("hmr/get-value") == "first"

        touch_hmr_plugin("second")
        # wait for the fs event + debounce + reload (real time)
        for _ in range(500):
            await asyncio.sleep(0.01)
            if ctx.bail("hmr/get-value") == "second":
                break
        assert ctx.bail("hmr/get-value") == "second"
    finally:
        os.path.exists(HMR_PLUGIN) and os.remove(HMR_PLUGIN)


async def _setup_hmr(monkeypatch):
    """Shared fixture: polling HMR over the fixture plugin, value == 'first'."""
    monkeypatch.setattr(hmr_module, "WATCHDOG_AVAILABLE", False)
    write_hmr_plugin("first")
    import sys

    sys.modules.pop("plugkit.tests.fixtures.hmr_plugin", None)
    clock = FakeClock()
    set_clock(clock)
    ctx = Context()
    loader = await install(ctx)
    loader.modules["__cordis_timer__"] = TimerService
    loader.modules["hmr"] = Hmr
    await loader.create({"name": "__cordis_timer__"})
    await loader.create({"name": "hmr", "config": {"debounce": 10}})
    await loader.create({"name": "plugkit.tests.fixtures.hmr_plugin"})
    for _ in range(50):
        await sleep()
    # let the poll register file snapshots before the change
    for _ in range(3):
        await clock.advance(20)
    entry = next(e for e in loader.entries() if e.options.get("name") == "plugkit.tests.fixtures.hmr_plugin")
    return ctx, loader, entry, clock


async def test_hmr_reload_preserves_entry_context(monkeypatch):
    try:
        ctx, loader, entry, clock = await _setup_hmr(monkeypatch)
        old_fiber = entry.fiber
        old_parent = old_fiber.parent
        assert ctx.bail("hmr/get-value") == "first"

        touch_hmr_plugin("second")
        for _ in range(50):
            await clock.advance(20)
        assert ctx.bail("hmr/get-value") == "second"
        assert entry.fiber is not old_fiber
        # JS: `oldFiber.parent.registry.plugin(...)` — the replacement keeps
        # the entry's context, so isolate/intercept still apply after reload
        assert entry.fiber.parent is old_parent
    finally:
        set_clock(None)
        os.path.exists(HMR_PLUGIN) and os.remove(HMR_PLUGIN)


async def test_hmr_failed_import_keeps_old_plugin(monkeypatch):
    try:
        ctx, loader, entry, clock = await _setup_hmr(monkeypatch)
        old_fiber = entry.fiber
        assert ctx.bail("hmr/get-value") == "first"

        write_raw("def broken(:\n")
        for _ in range(50):
            await clock.advance(20)

        # transaction aborts: the old fiber keeps serving and the previous
        # module object is restored into the import cache
        import sys

        assert entry.fiber is old_fiber
        assert ctx.bail("hmr/get-value") == "first"
        assert sys.modules["plugkit.tests.fixtures.hmr_plugin"].value == "first"
    finally:
        set_clock(None)
        os.path.exists(HMR_PLUGIN) and os.remove(HMR_PLUGIN)


async def test_hmr_failed_swap_rolls_back(monkeypatch):
    try:
        ctx, loader, entry, clock = await _setup_hmr(monkeypatch)
        old_fiber = entry.fiber
        assert ctx.bail("hmr/get-value") == "first"

        # imports fine, but exports no plugin (no `apply`) → the swap fails
        # after the old fiber was disposed → rollback rebuilds the old fiber
        write_raw('value = "second"\n')
        for _ in range(50):
            await clock.advance(20)
        for _ in range(50):
            await sleep()

        import sys

        assert entry.fiber is not old_fiber
        assert entry.fiber.uid is not None
        assert ctx.bail("hmr/get-value") == "first"
        assert sys.modules["plugkit.tests.fixtures.hmr_plugin"].value == "first"
    finally:
        set_clock(None)
        os.path.exists(HMR_PLUGIN) and os.remove(HMR_PLUGIN)
